variable "rg1_name" {}
variable "location" {}
variable "environment" {}
variable "vnet1_address_space" {}
variable "vnet1_subnet1_cidr" {}
variable "vm1_size" {}
variable "vm1_name" {}
variable "username" {}
variable "password" {}
variable "inbound_ports" {}